import os
from dotenv import load_dotenv

# Load .env file if present
load_dotenv()

MOHCCN_STANDARD_DEFINITION_XLSX_FILE_NAME = os.getenv('MOHCCN_STANDARD_DEFINITION_XLSX_FILE_NAME')
GENERATION_SETTINGS_VALIDATION_RULES_JSON_FILE_NAME = os.getenv('GENERATION_SETTINGS_VALIDATION_RULES_JSON_FILE_NAME')
GENERATED_VALIDATION_RULES_JSON_FILE_NAME = os.getenv('GENERATED_VALIDATION_RULES_JSON_FILE_NAME')
GENERATED_UNMAPPED_VOCAB_CSV_FILE_NAME = os.getenv('GENERATED_UNMAPPED_VOCAB_CSV_FILE_NAME')
GENERATED_MAPPED_VOCAB_FILE_NAME_PREFIX = os.getenv('GENERATED_MAPPED_VOCAB_FILE_NAME_PREFIX')
EXISTING_MAPPED_VOCAB_XLSX_FILE_NAME = os.getenv('EXISTING_MAPPED_VOCAB_XLSX_FILE_NAME')
MOHCCN_TO_OMOP_ETL_MODEL_XLSX_FILE_NAME = os.getenv('MOHCCN_TO_OMOP_ETL_MODEL_XLSX_FILE_NAME')
GENERATED_MOHCCN_TO_OMOP_ETL_SETTINGS_JSON_FILE_NAME = os.getenv('GENERATED_MOHCCN_TO_OMOP_ETL_SETTINGS_JSON_FILE_NAME')
VOCAB_SERVER_SEARCH_BY_TERM_URL = os.getenv('VOCAB_SERVER_SEARCH_BY_TERM_URL')
VOCAB_SERVER_SEARCH_BY_CODE_URL = os.getenv('VOCAB_SERVER_SEARCH_BY_CODE_URL')
CANDIG_API_SCHEMA_YML_URL = os.getenv('CANDIG_API_SCHEMA_YML_URL')